import type { Creator, GearListing, SecondHandListing, CreatorReel, Project, BookingPackage, EventPackage, ChatMessage, CreatorReview } from '@/types/creator';

const IMG = 'https://images.unsplash.com/photo-';
const avatars = [`${IMG}1507003211169-0a1dd7228f2d?w=200`,`${IMG}1494790108377-be9c29b29330?w=200`,`${IMG}1500648767791-00dcc994a43e?w=200`,`${IMG}1438761681033-6461ffad8d80?w=200`,`${IMG}1472099645785-5658abf4ff4e?w=200`,`${IMG}1534528741775-53994a69daeb?w=200`];
const portfolioImgs = [`${IMG}1516035069371-29a1b244cc32?w=600`,`${IMG}1502920917128-1aa500764cbd?w=600`,`${IMG}1554080353-a576cf803bda?w=600`,`${IMG}1542038784456-1ea8e935640e?w=600`,`${IMG}1519741497674-611481863552?w=600`,`${IMG}1505236858219-8359eb29e329?w=600`];

export const mockCreators: Creator[] = [
  { id:'c1', name:'Arjun Mehta', avatar:avatars[0], coverImage:portfolioImgs[0], category:'photographer', title:'Wedding & Portrait Photographer', bio:'Award-winning photographer specializing in candid wedding moments and editorial portraits.', location:'Mumbai, Maharashtra', coordinates:{lat:19.076,lng:72.8777}, rating:4.9, reviewCount:234, completedJobs:312, startingPrice:15000, hourlyRate:3000, availability:'available', verified:true, verificationLevel:'elite', trustScore:98, portfolio:portfolioImgs.slice(0,4), skills:['Wedding Photography','Portrait','Candid','Fashion'], styles:['cinematic','dramatic'], gear:['Sony A7R V','Canon RF 70-200mm'], languages:['Hindi','English','Marathi'], experience:8, responseTime:'< 1 hour', featured:true, tags:['top-rated','wedding-expert'], socialLinks:{instagram:'@arjunmehta'}},
  { id:'c2', name:'Priya Sharma', avatar:avatars[1], coverImage:portfolioImgs[1], category:'videographer', title:'Cinematic Filmmaker', bio:'Creating cinematic stories for brands and weddings with a focus on emotion and narrative.', location:'Delhi, NCR', coordinates:{lat:28.6139,lng:77.209}, rating:4.8, reviewCount:178, completedJobs:245, startingPrice:25000, hourlyRate:5000, availability:'available', verified:true, verificationLevel:'pro', trustScore:95, portfolio:portfolioImgs.slice(1,5), skills:['Cinematic Films','Commercials','Wedding Films','Music Videos'], styles:['cinematic','moody'], gear:['Sony FX6','DJI RS3 Pro','Aputure 600d'], languages:['Hindi','English'], experience:6, responseTime:'< 2 hours', featured:true, tags:['filmmaker','cinematic'], socialLinks:{instagram:'@priyafilms',youtube:'PriyaSharmaFilms'}},
  { id:'c3', name:'Rahul Verma', avatar:avatars[2], coverImage:portfolioImgs[2], category:'drone_operator', title:'Licensed Drone Pilot & Aerial Cinematographer', bio:'DGCA certified drone pilot with 2000+ flight hours. Specializing in real estate and event aerials.', location:'Bangalore, Karnataka', coordinates:{lat:12.9716,lng:77.5946}, rating:4.7, reviewCount:92, completedJobs:156, startingPrice:12000, hourlyRate:4000, availability:'busy', verified:true, verificationLevel:'pro', trustScore:93, portfolio:portfolioImgs.slice(2,6), skills:['Aerial Photography','Aerial Videography','Mapping','Inspection'], styles:['cinematic','dramatic'], gear:['DJI Mavic 3 Pro','DJI Inspire 3','DJI Mini 4 Pro'], languages:['Hindi','English','Kannada'], experience:5, responseTime:'< 3 hours', featured:true, tags:['drone-expert','aerial'], socialLinks:{instagram:'@rahulaerial'}},
  { id:'c4', name:'Sneha Patel', avatar:avatars[3], coverImage:portfolioImgs[3], category:'editor', title:'Senior Photo & Video Editor', bio:'Expert retoucher and colorist. Delivering magazine-quality edits with fast turnaround.', location:'Hyderabad, Telangana', coordinates:{lat:17.385,lng:78.4867}, rating:4.9, reviewCount:312, completedJobs:890, startingPrice:2000, hourlyRate:800, availability:'available', verified:true, verificationLevel:'elite', trustScore:99, portfolio:portfolioImgs.slice(0,3), skills:['Photo Retouching','Color Grading','Video Editing','Compositing'], styles:['bright_airy','editorial','fine_art'], gear:['iMac Pro','Wacom Cintiq'], languages:['Hindi','English','Telugu'], experience:7, responseTime:'< 30 mins', featured:true, tags:['fast-delivery','top-editor'], socialLinks:{instagram:'@snehapatel.edits'}},
  { id:'c5', name:'Vikram Singh', avatar:avatars[4], coverImage:portfolioImgs[4], category:'videographer', title:'Commercial Videographer', bio:'Creating impactful brand videos, product films, and corporate content.', location:'Chennai, Tamil Nadu', coordinates:{lat:13.0827,lng:80.2707}, rating:4.6, reviewCount:145, completedJobs:198, startingPrice:20000, hourlyRate:4000, availability:'offline', verified:true, verificationLevel:'id_verified', trustScore:88, portfolio:portfolioImgs.slice(1,4), skills:['Commercials','Product Videos','Corporate','Documentaries'], styles:['minimal','documentary'], gear:['Canon C70','Canon RF 24-70mm'], languages:['Hindi','English','Tamil'], experience:9, responseTime:'< 4 hours', featured:false, tags:['commercial','brand'], socialLinks:{instagram:'@vikramsingh.films'}},
  { id:'c6', name:'Ananya Krishnan', avatar:avatars[5], coverImage:portfolioImgs[5], category:'model', title:'Fashion & Commercial Model', bio:'Professional model with 5+ years in fashion editorials, e-commerce, and brand campaigns.', location:'Pune, Maharashtra', coordinates:{lat:18.5204,lng:73.8567}, rating:4.8, reviewCount:88, completedJobs:220, startingPrice:10000, hourlyRate:3500, availability:'available', verified:true, verificationLevel:'pro', trustScore:94, portfolio:portfolioImgs, skills:['Fashion','Editorial','E-commerce','Bridal'], styles:['editorial','fine_art'], gear:[], languages:['Hindi','English','Malayalam'], experience:5, responseTime:'< 1 hour', featured:true, tags:['fashion-model','editorial'], socialLinks:{instagram:'@ananyakrishnan'}},
  { id:'c7', name:'Karthik Rajan', avatar:avatars[0], coverImage:portfolioImgs[0], category:'photographer', title:'Product & Food Photographer', bio:'Specialized in e-commerce product photography and food styling shots.', location:'Coimbatore, Tamil Nadu', coordinates:{lat:11.0168,lng:76.9558}, rating:4.5, reviewCount:67, completedJobs:340, startingPrice:5000, hourlyRate:1500, availability:'available', verified:true, verificationLevel:'id_verified', trustScore:86, portfolio:portfolioImgs.slice(0,3), skills:['Product Photography','Food Photography','E-commerce','Flat Lay'], styles:['bright_airy','minimal'], gear:['Canon R6 II','Godox SL200W'], languages:['Tamil','English'], experience:4, responseTime:'< 2 hours', featured:false, tags:['product','food'], socialLinks:{instagram:'@karthikshots'}},
  { id:'c8', name:'Meera Nair', avatar:avatars[3], coverImage:portfolioImgs[4], category:'makeup_artist', title:'Bridal & Fashion Makeup Artist', bio:'Celebrity makeup artist specializing in bridal and high-fashion looks.', location:'Kochi, Kerala', coordinates:{lat:9.9312,lng:76.2673}, rating:4.9, reviewCount:156, completedJobs:450, startingPrice:8000, hourlyRate:2500, availability:'available', verified:true, verificationLevel:'elite', trustScore:97, portfolio:portfolioImgs.slice(2,6), skills:['Bridal Makeup','Fashion','Editorial','Airbrush'], styles:['editorial','dramatic'], gear:['MAC Pro Kit','Airbrush System'], languages:['Hindi','English','Malayalam'], experience:10, responseTime:'< 1 hour', featured:true, tags:['bridal-expert','celebrity'], socialLinks:{instagram:'@meeranair.mua'}},
];

export const mockGearListings: GearListing[] = [
  { id:'g1', name:'Sony A7S III', brand:'Sony', category:'Camera', image:`${IMG}1516035069371-29a1b244cc32?w=500`, images:[], dailyRate:3500, hourlyRate:500, weeklyRate:18000, securityDeposit:25000, available:true, rating:4.9, reviewCount:45, location:'Mumbai', coordinates:{lat:19.076,lng:72.877}, owner:{name:'Arjun M.',avatar:avatars[0],rating:4.9,verified:true}, condition:'Excellent', description:'Low-light beast, perfect for video shoots', specs:{Sensor:'12.1MP Full Frame',Video:'4K 120fps'}, deliveryAvailable:true, pickupOnly:false, damageProtection:true },
  { id:'g2', name:'DJI Inspire 3', brand:'DJI', category:'Drone', image:`${IMG}1542038784456-1ea8e935640e?w=500`, images:[], dailyRate:8000, hourlyRate:1200, weeklyRate:45000, securityDeposit:50000, available:true, rating:4.8, reviewCount:23, location:'Delhi', coordinates:{lat:28.613,lng:77.209}, owner:{name:'Rahul V.',avatar:avatars[2],rating:4.7,verified:true}, condition:'Like New', description:'Professional cinema drone with 8K camera', specs:{Camera:'8K Full Frame',FlightTime:'28 min'}, deliveryAvailable:false, pickupOnly:true, damageProtection:true },
  { id:'g3', name:'Canon RF 70-200mm f/2.8L', brand:'Canon', category:'Lens', image:`${IMG}1502920917128-1aa500764cbd?w=500`, images:[], dailyRate:2000, hourlyRate:350, weeklyRate:10000, securityDeposit:15000, available:true, rating:4.9, reviewCount:67, location:'Bangalore', coordinates:{lat:12.971,lng:77.594}, owner:{name:'Priya S.',avatar:avatars[1],rating:4.8,verified:true}, condition:'Excellent', description:'Sharpest zoom lens for portraits and events', specs:{Aperture:'f/2.8',Mount:'Canon RF'}, deliveryAvailable:true, pickupOnly:false, damageProtection:true },
  { id:'g4', name:'Aputure 600d Pro', brand:'Aputure', category:'Lighting', image:`${IMG}1554080353-a576cf803bda?w=500`, images:[], dailyRate:2500, hourlyRate:400, weeklyRate:12000, securityDeposit:15000, available:false, rating:4.7, reviewCount:34, location:'Chennai', coordinates:{lat:13.082,lng:80.270}, owner:{name:'Vikram S.',avatar:avatars[4],rating:4.6,verified:true}, condition:'Good', description:'600W daylight COB with Bowens mount', specs:{Power:'600W',CRI:'96+'}, deliveryAvailable:true, pickupOnly:false, damageProtection:false },
  { id:'g5', name:'DJI RS 4 Pro', brand:'DJI', category:'Gimbal', image:`${IMG}1505236858219-8359eb29e329?w=500`, images:[], dailyRate:1500, hourlyRate:250, weeklyRate:8000, securityDeposit:10000, available:true, rating:4.8, reviewCount:52, location:'Hyderabad', coordinates:{lat:17.385,lng:78.486}, owner:{name:'Sneha P.',avatar:avatars[3],rating:4.9,verified:true}, condition:'Like New', description:'4.5kg payload gimbal with LiDAR focus', specs:{Payload:'4.5kg',Battery:'12 hrs'}, deliveryAvailable:true, pickupOnly:false, damageProtection:true },
];

export const mockSecondHandListings: SecondHandListing[] = [
  { id:'sh1', name:'Sony Alpha A7 III Body', brand:'Sony', category:'Camera', image:`${IMG}1516035069371-29a1b244cc32?w=500`, images:[], price:85000, originalPrice:150000, marketValue:90000, condition:'Excellent', conditionScore:92, seller:{id:'s1',name:'Amit K.',avatar:avatars[0],rating:4.8,totalSales:23,verified:true}, description:'Well-maintained, barely used for personal projects. Shutter count 12K.', specs:{Sensor:'24.2MP',Shutter:'12,000 clicks'}, purchaseDate:'2024-03-15', shutterCount:12000, accessories:['2 Batteries','Charger','Strap','Box'], warranty:'3 months seller warranty', negotiable:true, escrowSupported:true, location:'Mumbai', createdAt:'2026-05-10' },
  { id:'sh2', name:'Canon EOS R5 Body', brand:'Canon', category:'Camera', image:`${IMG}1502920917128-1aa500764cbd?w=500`, images:[], price:195000, originalPrice:340000, marketValue:210000, condition:'Like New', conditionScore:97, seller:{id:'s2',name:'Deepika R.',avatar:avatars[1],rating:4.9,totalSales:45,verified:true}, description:'Mint condition R5 with original packaging. Used for studio work only.', specs:{Sensor:'45MP',Video:'8K RAW'}, purchaseDate:'2025-01-20', shutterCount:5000, accessories:['Battery','Charger','Box','Warranty Card'], warranty:'6 months seller warranty', negotiable:false, escrowSupported:true, location:'Delhi', createdAt:'2026-05-08' },
  { id:'sh3', name:'DJI Mavic 3 Classic', brand:'DJI', category:'Drone', image:`${IMG}1542038784456-1ea8e935640e?w=500`, images:[], price:72000, originalPrice:115000, marketValue:78000, condition:'Good', conditionScore:82, seller:{id:'s3',name:'Suresh M.',avatar:avatars[2],rating:4.5,totalSales:12,verified:true}, description:'Reliable Mavic 3 with Hasselblad camera. Minor cosmetic wear on arms.', specs:{Camera:'20MP Hasselblad',FlightTime:'46 min'}, purchaseDate:'2024-08-10', usageHours:120, accessories:['3 Batteries','Controller','Case'], warranty:'No warranty', negotiable:true, escrowSupported:true, location:'Bangalore', createdAt:'2026-05-05' },
];

export const mockReels: CreatorReel[] = [
  { id:'r1', creator:{id:'c1',name:'Arjun Mehta',avatar:avatars[0],verified:true,category:'photographer'}, thumbnail:`${IMG}1519741497674-611481863552?w=400`, videoUrl:'', caption:'Golden hour magic at Marine Drive 🌅 #weddingphotography #mumbai', tags:['wedding','goldenhour','portrait'], likes:2340, comments:189, shares:67, saves:445, views:45000, duration:'0:28', createdAt:'2026-05-20', trending:true, type:'highlight' },
  { id:'r2', creator:{id:'c2',name:'Priya Sharma',avatar:avatars[1],verified:true,category:'videographer'}, thumbnail:`${IMG}1505236858219-8359eb29e329?w=400`, videoUrl:'', caption:'BTS of our latest commercial shoot for a luxury brand ✨', tags:['bts','commercial','filmmaking'], likes:1890, comments:145, shares:89, saves:320, views:38000, duration:'0:45', createdAt:'2026-05-19', trending:true, type:'bts' },
  { id:'r3', creator:{id:'c4',name:'Sneha Patel',avatar:avatars[3],verified:true,category:'editor'}, thumbnail:`${IMG}1554080353-a576cf803bda?w=400`, videoUrl:'', caption:'Before vs After color grade — Cinematic LUT breakdown 🎬', tags:['colorgrading','editing','tutorial'], likes:3200, comments:267, shares:234, saves:890, views:67000, duration:'0:32', createdAt:'2026-05-18', trending:true, type:'before_after' },
  { id:'r4', creator:{id:'c3',name:'Rahul Verma',avatar:avatars[2],verified:true,category:'drone_operator'}, thumbnail:`${IMG}1542038784456-1ea8e935640e?w=400`, videoUrl:'', caption:'Aerial cinematic of Hampi ruins — DJI Inspire 3 🚁', tags:['drone','aerial','cinematic'], likes:4500, comments:312, shares:178, saves:1200, views:89000, duration:'0:55', createdAt:'2026-05-17', trending:true, type:'cinematic' },
  { id:'r5', creator:{id:'c6',name:'Ananya Krishnan',avatar:avatars[5],verified:true,category:'model'}, thumbnail:`${IMG}1534528741775-53994a69daeb?w=400`, videoUrl:'', caption:'Fashion editorial BTS with amazing team 💃', tags:['fashion','model','editorial'], likes:5600, comments:423, shares:345, saves:1560, views:120000, duration:'0:22', createdAt:'2026-05-16', trending:true, type:'bts' },
];

export const mockBookingPackages: BookingPackage[] = [
  { id:'bp1', name:'Essential Wedding Package', eventType:'wedding', description:'Perfect for intimate weddings. 8 hours of coverage with 1 photographer.', price:35000, duration:'8 hours', deliverables:['200+ edited photos','Online gallery','USB drive'], includes:['1 Photographer','Basic retouching','Same-day preview'], popular:false },
  { id:'bp2', name:'Premium Wedding Package', eventType:'wedding', description:'Complete wedding coverage with photo + video team.', price:85000, duration:'Full day (12 hrs)', deliverables:['500+ edited photos','Cinematic highlight film','Full ceremony video','Photo album'], includes:['2 Photographers','1 Videographer','Drone coverage','Advanced editing'], popular:true },
  { id:'bp3', name:'Product Shoot Basic', eventType:'product_shoot', description:'Clean product photography for e-commerce.', price:8000, duration:'4 hours', deliverables:['30 product images','White background','Lifestyle shots'], includes:['1 Photographer','Studio lighting','Basic retouching'], popular:false },
  { id:'bp4', name:'Music Video Production', eventType:'music_video', description:'Full music video production with cinematic quality.', price:150000, duration:'2-3 days', deliverables:['4K Music Video','BTS content','Poster shots'], includes:['Director','Cinematographer','Editor','Drone operator','Lighting'], popular:true },
  { id:'bp5', name:'Corporate Event Coverage', eventType:'corporate', description:'Professional coverage for corporate events and conferences.', price:25000, duration:'6 hours', deliverables:['150+ photos','Event highlight reel','Speaker portraits'], includes:['1 Photographer','1 Videographer','Same-day edits'], popular:false },
];

export const mockEventPackages: EventPackage[] = [
  { id:'ep1', eventType:'wedding', name:'Royal Wedding Collection', description:'Complete wedding coverage with premium team', startingPrice:50000, maxPrice:500000, duration:'1-3 days', teamSize:'4-10', deliverables:['Cinematic film','500+ photos','Drone shots','Album'], includes:['Photographers','Videographers','Drone','Editor','Album design'], popular:true, image:`${IMG}1519741497674-611481863552?w=500` },
  { id:'ep2', eventType:'birthday', name:'Birthday Celebration Pack', description:'Fun & candid party coverage', startingPrice:10000, maxPrice:50000, duration:'3-6 hours', teamSize:'1-3', deliverables:['100+ photos','Party highlights reel','Boomerangs'], includes:['Photographer','Videographer','Props'], popular:false, image:`${IMG}1505236858219-8359eb29e329?w=500` },
  { id:'ep3', eventType:'fashion', name:'Fashion Editorial Shoot', description:'High-fashion editorial and lookbook production', startingPrice:30000, maxPrice:200000, duration:'1 day', teamSize:'3-8', deliverables:['50+ retouched images','Lookbook layout','BTS video'], includes:['Photographer','Stylist','MUA','Model','Editor'], popular:true, image:`${IMG}1534528741775-53994a69daeb?w=500` },
  { id:'ep4', eventType:'real_estate', name:'Property Showcase', description:'Aerial and interior property photography', startingPrice:15000, maxPrice:80000, duration:'4-8 hours', teamSize:'2-4', deliverables:['HDR photos','Virtual tour','Drone footage','Floor plan shots'], includes:['Photographer','Drone operator','Editor'], popular:false, image:`${IMG}1554080353-a576cf803bda?w=500` },
  { id:'ep5', eventType:'commercial', name:'Brand Campaign', description:'Complete brand and advertising content production', startingPrice:75000, maxPrice:500000, duration:'2-5 days', teamSize:'5-15', deliverables:['Campaign visuals','Social media content','TVC','BTS'], includes:['Director','DOP','Models','Styling','Post-production'], popular:true, image:`${IMG}1502920917128-1aa500764cbd?w=500` },
];

export const mockProjects: Project[] = [
  { id:'pr1', title:'Luxury Resort Brand Campaign', description:'Complete visual campaign for a 5-star resort chain including photos, videos, and drone footage.', coverImage:portfolioImgs[0], creator:{id:'c2',name:'Priya Sharma',avatar:avatars[1]}, members:[{id:'c2',name:'Priya Sharma',avatar:avatars[1],role:'videographer',joinedAt:'2026-05-01'},{id:'c1',name:'Arjun Mehta',avatar:avatars[0],role:'photographer',joinedAt:'2026-05-01'},{id:'c3',name:'Rahul Verma',avatar:avatars[2],role:'drone_operator',joinedAt:'2026-05-02'},{id:'c4',name:'Sneha Patel',avatar:avatars[3],role:'editor',joinedAt:'2026-05-02'}], tasks:[{id:'t1',title:'Location scouting',assignee:{id:'c2',name:'Priya Sharma',avatar:avatars[1],role:'videographer',joinedAt:''},status:'done',priority:'high',deadline:'2026-05-10',description:'Scout 5 locations'},{id:'t2',title:'Aerial shots - Pool & Beach',assignee:{id:'c3',name:'Rahul Verma',avatar:avatars[2],role:'drone_operator',joinedAt:''},status:'in_progress',priority:'high',deadline:'2026-05-25',description:'Capture drone footage'},{id:'t3',title:'Color grading & edit',assignee:{id:'c4',name:'Sneha Patel',avatar:avatars[3],role:'editor',joinedAt:''},status:'todo',priority:'medium',deadline:'2026-06-01',description:'Final color grading'}], files:[{id:'f1',name:'mood-board.pdf',type:'pdf',size:'4.2 MB',uploadedBy:'Priya',uploadedAt:'2026-05-01',url:'#'},{id:'f2',name:'shot-list.xlsx',type:'xlsx',size:'1.1 MB',uploadedBy:'Arjun',uploadedAt:'2026-05-03',url:'#'}], status:'active', deadline:'2026-06-15', createdAt:'2026-05-01', progress:45, category:'commercial' },
  { id:'pr2', title:'Wedding Film - Raj & Meera', description:'Destination wedding coverage in Udaipur with full photo and video team.', coverImage:portfolioImgs[4], creator:{id:'c1',name:'Arjun Mehta',avatar:avatars[0]}, members:[{id:'c1',name:'Arjun Mehta',avatar:avatars[0],role:'photographer',joinedAt:'2026-04-15'},{id:'c2',name:'Priya Sharma',avatar:avatars[1],role:'videographer',joinedAt:'2026-04-15'},{id:'c8',name:'Meera Nair',avatar:avatars[3],role:'makeup_artist',joinedAt:'2026-04-20'}], tasks:[{id:'t4',title:'Pre-wedding shoot',assignee:{id:'c1',name:'Arjun Mehta',avatar:avatars[0],role:'photographer',joinedAt:''},status:'done',priority:'high',deadline:'2026-05-15',description:'Pre-wedding at fort'},{id:'t5',title:'Ceremony coverage',assignee:{id:'c2',name:'Priya Sharma',avatar:avatars[1],role:'videographer',joinedAt:''},status:'todo',priority:'urgent',deadline:'2026-06-01',description:'Full ceremony video'}], files:[], status:'active', deadline:'2026-06-10', createdAt:'2026-04-15', progress:30, category:'wedding' },
];

export const mockCreatorReviews: CreatorReview[] = [
  { id:'rv1', reviewerName:'Ankit & Pooja', reviewerAvatar:'', rating:5, comment:'Arjun captured our wedding beautifully! Every shot tells a story. Absolutely recommend for any wedding.', date:'2026-05-10', eventType:'wedding', verified:true, images:[] },
  { id:'rv2', reviewerName:'Brand XYZ', reviewerAvatar:'', rating:5, comment:'Priya delivered an exceptional commercial film. Professional, creative, and great to work with.', date:'2026-05-05', eventType:'commercial', verified:true, images:[] },
  { id:'rv3', reviewerName:'Real Estate Corp', reviewerAvatar:'', rating:4, comment:'Rahul\'s drone work is top notch. The aerial footage of our properties looked amazing.', date:'2026-04-28', eventType:'real_estate', verified:true, images:[] },
  { id:'rv4', reviewerName:'Fashion Studio', reviewerAvatar:'', rating:5, comment:'Sneha\'s editing is world-class. Quick turnaround and the color grading was exactly what we wanted.', date:'2026-04-20', eventType:'fashion', verified:true, images:[] },
];

export const mockChatMessages: ChatMessage[] = [
  { id:'m1', senderId:'client', senderName:'You', senderAvatar:'', content:'Hi! I\'m interested in booking a wedding shoot for June 15th. Are you available?', timestamp:'2026-05-20T10:30:00', read:true, type:'text' },
  { id:'m2', senderId:'c1', senderName:'Arjun Mehta', senderAvatar:avatars[0], content:'Hey! Yes, June 15th is available. I\'d love to know more about your wedding — venue, expected guest count, and what coverage you need.', timestamp:'2026-05-20T10:35:00', read:true, type:'text' },
  { id:'m3', senderId:'client', senderName:'You', senderAvatar:'', content:'It\'s at a resort in Udaipur. Around 200 guests. We need full day coverage + drone.', timestamp:'2026-05-20T10:40:00', read:true, type:'text' },
  { id:'m4', senderId:'c1', senderName:'Arjun Mehta', senderAvatar:avatars[0], content:'Perfect! I\'d recommend my Premium Wedding Package — it includes 2 photographers, a videographer, drone coverage, and a cinematic highlight film. Let me send you a detailed quote.', timestamp:'2026-05-20T10:45:00', read:true, type:'text' },
];
